services:
  stream-demo:
    container_name: 'stream-demo'
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    logging:
      driver:     "json-file"
      options:
        max-size: "10m"
        max-file: "3"
